import Footer from "@/components/layouts/footer";
import Header from "@/components/layouts/header";
import "bootstrap/dist/css/bootstrap.css";
import { aeonik, helvetica } from "../lib/fonts";
import { cn } from "../lib/utils";
import "../styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(aeonik.variable, helvetica.variable)}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
